services:
  _defaults:
    autowire: true
    autoconfigure: true

  Nordwerk\WithdrawalBundle\:
    resource: "../src/"
    exclude: "../src/{ContaoManager,DependencyInjection,NordwerkWithdrawalBundle.php}"

  Nordwerk\WithdrawalBundle\Mail\WithdrawalMailer:
    public: true
    arguments:
      $merchantEmail: ""
      $settings: '@Nordwerk\WithdrawalBundle\Settings\WithdrawalSettings'

  Nordwerk\WithdrawalBundle\InsertTag\WithdrawalLinkInsertTag:
    arguments:
      $path: "/withdrawal"
      $settings: '@Nordwerk\WithdrawalBundle\Settings\WithdrawalSettings'

  Nordwerk\WithdrawalBundle\Settings\WithdrawalSettings:
    public: true

  Nordwerk\WithdrawalBundle\Mail\MailDocument:
    public: true
